export const  listTrips = 
    [
        {
            "Trip": {
                "id": 10072608,
                "trip_status": 0,
                "is_vat": 0,
                "full_name_guest":"Nguyen DUng",
                "time_start": "2025-10-30 13:00:00",
                "time_sell": "2025-10-30 08:50:00",
                "price_sell": 160,
                "price_driver_priority": 0,
                "price_driver_vip": 0,
                "price_driver_normal": 160,
                "type_car_id": 1,
                "place_start": "Trung Tâm Hội Nghị Quốc Gia Việt Nam, Mễ Trì, Từ Liêm, Hà Nội",
                "place_end": "Sân Bay Nội Bài (HAN), Sóc Sơn, Hà Nội",
                "is_one_way": 1,
                "time_sell_display": 29363400,
                "total_time_sell_priority": 0,
                "time_sell_driver_priority": "2025-10-30 08:50:00",
                "time_sell_driver_priority_list": "2025-10-30 08:50:00",
                "time_sell_driver_vip": "2025-10-30 08:50:00",
                "time_sell_driver_normal": "1970-01-01 08:00:00",
                "point": 0,
                "point_time": 0,
                "point_driver_priority": 0,
                "point_driver_priority_list": 0,
                "point_driver_vip": 0,
                "point_driver_normal": 0,
                "super_vip_drivers": "",
                "note": "",
                "price_note": "Giá trên đã bao gồm phí cao tốc, phí ra vào SB",
                "service_note1": "",
                "service_note2": "",
                "service_note3": "",
                "buy_button": false,
                "display": true,
                "is_waitting": true,
                "level_sell": 3,
                "driver_priority_id": 0,
                "group_priority_name": "",
                "driver_priority_list": "",
                "driver_limited": "2,6406,7887"
            }
        },
        {
            "Trip": {
                "id": 10068539,
                "trip_status": 0,
                "is_vat": 1,
                "full_name_guest":"Nguyen DUng",
                "time_start": "2025-10-30 13:40:00",
                "time_sell": "2025-10-30 08:40:00",
                "price_sell": 830,
                "price_driver_priority": 0,
                "price_driver_vip": 0,
                "price_driver_normal": 830,
                "type_car_id": 1,
                "place_start": "Sân Bay Nội Bài, Hà Nội",
                "place_end": "Thành Phố Ninh Bình, Ninh Bình",
                "is_one_way": 1,
                "time_sell_display": 29363440,
                "total_time_sell_priority": 0,
                "time_sell_driver_priority": "2025-10-30 08:40:00",
                "time_sell_driver_priority_list": "2025-10-30 08:40:00",
                "time_sell_driver_vip": "2025-10-30 08:40:00",
                "time_sell_driver_normal": "1970-01-01 08:00:00",
                "point": 0,
                "point_time": 0,
                "point_driver_priority": 0,
                "point_driver_priority_list": 0,
                "point_driver_vip": 0,
                "point_driver_normal": 0,
                "super_vip_drivers": "",
                "note": "",
                "price_note": "Giá trên đã bao gồm phí cao tốc, phí ra vào SB",
                "service_note1": "",
                "service_note2": "",
                "service_note3": "",
                "buy_button": true,
                "display": true,
                "is_waitting": false,
                "level_sell": 3,
                "driver_priority_id": 0,
                "group_priority_name": "",
                "driver_priority_list": "",
                "driver_limited": "2,6406,7887"
            }
        },
        {
            "Trip": {
                "id": 10072639,
                "trip_status": 0,
                "is_vat": 0,
                "full_name_guest":"Nguyen DUng",
                "time_start": "2025-10-30 14:00:00",
                "time_sell": "2025-10-30 08:08:20",
                "price_sell": 190,
                "price_driver_priority": 0,
                "price_driver_vip": 0,
                "price_driver_normal": 190,
                "type_car_id": 1,
                "place_start": "HUDxx Linh Đàm, Linh Đường, Khu đô Thị Tây Nam Linh Đàm, Hoàng Liệt, Hoàng Mai, Hà Nội",
                "place_end": "Sân Bay Nội Bài (HAN), Sóc Sơn, Hà Nội",
                "is_one_way": 1,
                "time_sell_display": 29363460,
                "total_time_sell_priority": 0,
                "time_sell_driver_priority": "2025-10-30 11:00:00",
                "time_sell_driver_priority_list": "2025-10-30 11:00:00",
                "time_sell_driver_vip": "2025-10-30 11:00:00",
                "time_sell_driver_normal": "1970-01-01 08:00:00",
                "point": 0,
                "point_time": 0,
                "point_driver_priority": 0,
                "point_driver_priority_list": 0,
                "point_driver_vip": 0,
                "point_driver_normal": 0,
                "super_vip_drivers": "",
                "note": "note chuyen",
                "price_note": "Giá trên đã bao gồm phí cao tốc, phí ra vào SB",
                "service_note1": "",
                "service_note2": "",
                "service_note3": "",
                "buy_button": false,
                "display": true,
                "is_waitting": true,
                "level_sell": 3,
                "driver_priority_id": 0,
                "group_priority_name": "",
                "driver_priority_list": "",
                "driver_limited": "2,6406,7887"
            }
        },
        {
            "Trip": {
                "id": 10072525,
                "trip_status": 0,
                "is_vat": 0,
                "full_name_guest":"Nguyen DUng",
                "time_start": "2025-10-30 14:00:00",
                "time_sell": "2025-10-30 11:00:00",
                "price_sell": 170,
                "price_driver_priority": 0,
                "price_driver_vip": 0,
                "price_driver_normal": 170,
                "type_car_id": 1,
                "place_start": "Sân Bay Nội Bài, Hà Nội",
                "place_end": "xx Phố Miếu Đầm, Mễ Trì, Nam Từ Liêm, Hà Nội",
                "is_one_way": 1,
                "time_sell_display": 29363460,
                "total_time_sell_priority": 0,
                "time_sell_driver_priority": "2025-10-30 11:00:00",
                "time_sell_driver_priority_list": "2025-10-30 11:00:00",
                "time_sell_driver_vip": "2025-10-30 11:00:00",
                "time_sell_driver_normal": "1970-01-01 08:00:00",
                "point": 0,
                "point_time": 0,
                "point_driver_priority": 0,
                "point_driver_priority_list": 0,
                "point_driver_vip": 0,
                "point_driver_normal": 0,
                "super_vip_drivers": "",
                "note": "VN212",
                "price_note": "Giá trên đã bao gồm phí cao tốc, phí ra vào SB",
                "service_note1": "sdfdsfds",
                "service_note2": "sdfsdfds",
                "service_note3": "sdfdsfds",
                "buy_button": false,
                "display": true,
                "is_waitting": true,
                "level_sell": 3,
                "driver_priority_id": 0,
                "group_priority_name": "",
                "driver_priority_list": "",
                "driver_limited": "2,6406,7887"
            }
        }
]