export const groupsArea = [
  {
    id: 1,
    type_car_name: 'Xe 4 chỗ',
    group_type_car_name: 4,
    group_area_name: 'Hà Nội',
    count_trips: '120',
  },
  {
    id: 2,
    type_car_name: 'Xe 7 chỗ',
    group_area_name: 'Hà Nội',
    count_trips: '15',
    is_read: false,
  },
  {
    id: 3,
    type_car_name: 'Xe 16 chỗ',
    group_area_name: 'Hà Nội',
    count_trips: '15',
    is_read: false,
  },
  {
    id: 4,
    type_car_name: 'Xe 29 chỗ',
    group_area_name: 'Hà Nội',
    count_trips: '30',
  },
  {
    id: 5,
    type_car_name: 'Xe 45 chỗ',
    group_area_name: 'Hà Nội',
    count_trips: '12',
    is_read: false,
  },
  {
    id: 6,
    type_car_name: 'Xe Limousine',
    group_area_name: 'Hà Nội',
    count_trips: '130',
    is_read: true,
  },
  {
    id: 7,
    type_car_name: 'Xe Limousine',
    group_area_name: 'Nam Định',
    count_trips: '24',
    is_read: false,
  },
];

export const listTrips = [
  {
    Trip: {
      id: 10068539,
      trip_status: 0,
      sold: 0,
      driver_buy: '',
      is_vat: 1,
      direction: 2,
      guests: 1,
      full_name_driver_owner: 'Nguyen DUng',
      time_start: '2025-10-30 13:40:00',
      time_sell: '2025-10-30 08:40:00',
      price_sell: 830,
      price_driver_priority: 0,
      price_driver_vip: 0,
      price_driver_normal: 830,
      type_car_name_id: 1,
      place_start: 'Sân Bay Nội Bài, Hà Nội',
      place_end: 'Thành Phố Ninh Bình, Ninh Bình',
      is_one_way: 1,
      time_sell_display: 29363440,
      total_time_sell_priority: 0,
      time_sell_driver_priority: '2025-10-30 08:40:00',
      time_sell_driver_priority_list: '2025-10-30 08:40:00',
      time_sell_driver_vip: '2025-10-30 08:40:00',
      time_sell_driver_normal: '1970-01-01 08:00:00',
      point: 0,
      point_time: 0,
      point_driver_priority: 0,
      point_driver_priority_list: 0,
      point_driver_vip: 0,
      point_driver_normal: 0,
      super_vip_drivers: '',
      note: 'Xe 7 chỗ',
      price_note: 'Giá trên đã bao gồm phí cao tốc, phí ra vào SB',

      buy_button: true,
      display: true,
      is_waitting: false,
      level_sell: 3,
      driver_priority_id: 0,
      group_priority_name: '',
      driver_priority_list: '',
      driver_limited: '2,6406,7887',
    },
  },
  {
    Trip: {
      id: 100726359,
      trip_status: 0,
      sold: 0,
      driver_buy: '',
      is_vat: 0,
      guests: 4,
      direction: 2,
      full_name_driver_owner: 'Nguyen DUng',
      time_start: '2025-10-30 14:00:00',
      time_sell: '2025-10-30 08:08:20',
      price_sell: 190,
      price_driver_priority: 0,
      price_driver_vip: 0,
      price_driver_normal: 190,
      type_car_name_id: 1,
      place_start:
        'HUDxx Linh Đàm, Linh Đường, Khu đô Thị Tây Nam Linh Đàm, Hoàng Liệt, Hoàng Mai, Hà Nội',
      place_end: 'Sân Bay Nội Bài (HAN), Sóc Sơn, Hà Nội',
      is_one_way: 1,
      time_sell_display: 29363460,
      total_time_sell_priority: 0,
      time_sell_driver_priority: '2025-10-30 11:00:00',
      time_sell_driver_priority_list: '2025-10-30 11:00:00',
      time_sell_driver_vip: '2025-10-30 11:00:00',
      time_sell_driver_normal: '1970-01-01 08:00:00',
      point: 0,
      point_time: 0,
      point_driver_priority: 0,
      point_driver_priority_list: 0,
      point_driver_vip: 0,
      point_driver_normal: 0,
      super_vip_drivers: '',
      note: 'Thân thiện, hỗ trợ hành lý',
      price_note: '',

      buy_button: false,
      display: true,
      is_waitting: true,
      level_sell: 3,
      driver_priority_id: 0,
      group_priority_name: '',
      driver_priority_list: '',
      driver_limited: '2,6406,7887',
    },
  },
  {
    Trip: {
      id: 100725825,
      trip_status: 0,
      sold: 0,
      driver_buy: '',
      is_vat: 0,
      guests: 2,
      direction: 1,
      full_name_driver_owner: 'Nguyen DUng',
      time_start: '2025-10-30 14:00:00',
      time_sell: '2025-10-30 11:00:00',
      price_sell: 170,
      price_driver_priority: 0,
      price_driver_vip: 0,
      price_driver_normal: 170,
      type_car_name_id: 1,
      place_start: 'Sân Bay Nội Bài, Hà Nội',
      place_end: 'xx Phố Miếu Đầm, Mễ Trì, Nam Từ Liêm, Hà Nội',
      is_one_way: 1,
      time_sell_display: 29363460,
      total_time_sell_priority: 0,
      time_sell_driver_priority: '2025-10-30 11:00:00',
      time_sell_driver_priority_list: '2025-10-30 11:00:00',
      time_sell_driver_vip: '2025-10-30 11:00:00',
      time_sell_driver_normal: '1970-01-01 08:00:00',
      point: 0,
      point_time: 0,
      point_driver_priority: 0,
      point_driver_priority_list: 0,
      point_driver_vip: 0,
      point_driver_normal: 0,
      super_vip_drivers: '',
      note: 'Xe mới, sạch sẽ',
      price_note: 'Giá trên đã bao gồm phí cao tốc, phí ra vào SB',

      buy_button: false,
      display: true,
      is_waitting: true,
      level_sell: 3,
      driver_priority_id: 0,
      group_priority_name: '',
      driver_priority_list: '',
      driver_limited: '2,6406,7887',
    },
  },
  {
    Trip: {
      id: 100685539,
      trip_status: 0,
      sold: 0,
      driver_buy: '',
      is_vat: 1,
      direction: 2,
      guests: 1,
      full_name_driver_owner: 'Nguyen DUng',
      time_start: '2025-10-30 13:40:00',
      time_sell: '2025-10-30 08:40:00',
      price_sell: 830,
      price_driver_priority: 0,
      price_driver_vip: 0,
      price_driver_normal: 830,
      type_car_name_id: 1,
      place_start: 'Sân Bay Nội Bài, Hà Nội',
      place_end: 'Thành Phố Ninh Bình, Ninh Bình',
      is_one_way: 1,
      time_sell_display: 29363440,
      total_time_sell_priority: 0,
      time_sell_driver_priority: '2025-10-30 08:40:00',
      time_sell_driver_priority_list: '2025-10-30 08:40:00',
      time_sell_driver_vip: '2025-10-30 08:40:00',
      time_sell_driver_normal: '1970-01-01 08:00:00',
      point: 0,
      point_time: 0,
      point_driver_priority: 0,
      point_driver_priority_list: 0,
      point_driver_vip: 0,
      point_driver_normal: 0,
      super_vip_drivers: '',
      note: '',
      price_note: 'Giá trên đã bao gồm phí cao tốc, phí ra vào SB',

      buy_button: true,
      display: true,
      is_waitting: false,
      level_sell: 3,
      driver_priority_id: 0,
      group_priority_name: '',
      driver_priority_list: '',
      driver_limited: '2,6406,7887',
    },
  },
  {
    Trip: {
      id: 100722639,
      trip_status: 0,
      is_vat: 0,
      sold: 0,
      driver_buy: '',
      guests: 4,
      direction: 2,
      full_name_driver_owner: 'Nguyen DUng',
      time_start: '2025-10-30 14:00:00',
      time_sell: '2025-10-30 08:08:20',
      price_sell: 190,
      price_driver_priority: 0,
      price_driver_vip: 0,
      price_driver_normal: 190,
      type_car_name_id: 1,
      place_start:
        'HUDxx Linh Đàm, Linh Đường, Khu đô Thị Tây Nam Linh Đàm, Hoàng Liệt, Hoàng Mai, Hà Nội',
      place_end: 'Sân Bay Nội Bài (HAN), Sóc Sơn, Hà Nội',
      is_one_way: 1,
      time_sell_display: 29363460,
      total_time_sell_priority: 0,
      time_sell_driver_priority: '2025-10-30 11:00:00',
      time_sell_driver_priority_list: '2025-10-30 11:00:00',
      time_sell_driver_vip: '2025-10-30 11:00:00',
      time_sell_driver_normal: '1970-01-01 08:00:00',
      point: 0,
      point_time: 0,
      point_driver_priority: 0,
      point_driver_priority_list: 0,
      point_driver_vip: 0,
      point_driver_normal: 0,
      super_vip_drivers: '',
      note: 'Không ngồi ghế cuối',
      price_note: 'Giá trên đã bao gồm phí cao tốc, phí ra vào SB',

      buy_button: false,
      display: true,
      is_waitting: true,
      level_sell: 3,
      driver_priority_id: 0,
      group_priority_name: '',
      driver_priority_list: '',
      driver_limited: '2,6406,7887',
    },
  },
  {
    Trip: {
      id: 100726078,
      group_type_car_name: 4,
      group_group_area_name: 'Hai Phong',
      sold: 1,
      driver_buy: 'Nguyễn Văn Long',
      is_vat: 0,
      direction: 1,
      full_name_driver_owner: 'Nguyen Dung',
      guests: 1,
      time_start: '2025-10-30 13:00:00',
      time_sell: '2025-10-30 08:50:00',
      price_sell: 160,
      place_start:
        'Trung Tâm Hội Nghị Quốc Gia Việt Nam, Mễ Trì, Từ Liêm, Hà Nội',
      place_end: 'Sân Bay Nội Bài (HAN), Sóc Sơn, Hà Nội',

      point: 0,

      note: 'Đón đúng giờ',
    },
  },
];
export const listHistoryTrips = [
  {
    Trip: {
      id: 10068539,
      trip_status: 0,
      sold: 0,
      driver_buy: '',
      is_vat: 1,
      direction: 2,
      guests: 1,
      full_name_driver_owner: 'Nguyen DUng',
      time_start: '2025-10-30 13:40:00',
      time_sell: '2025-10-30 08:40:00',
      price_sell: 830,
      price_driver_priority: 0,
      price_driver_vip: 0,
      price_driver_normal: 830,
      type_car_name_id: 1,
      place_start: 'Sân Bay Nội Bài, Hà Nội',
      place_end: 'Thành Phố Ninh Bình, Ninh Bình',
      is_one_way: 1,
      time_sell_display: 29363440,
      total_time_sell_priority: 0,
      time_sell_driver_priority: '2025-10-30 08:40:00',
      time_sell_driver_priority_list: '2025-10-30 08:40:00',
      time_sell_driver_vip: '2025-10-30 08:40:00',
      time_sell_driver_normal: '1970-01-01 08:00:00',
      point: 0,
      point_time: 0,
      point_driver_priority: 0,
      point_driver_priority_list: 0,
      point_driver_vip: 0,
      point_driver_normal: 0,
      super_vip_drivers: '',
      note: 'Xe 7 chỗ',
      price_note: 'Giá trên đã bao gồm phí cao tốc, phí ra vào SB',

      buy_button: true,
      display: true,
      is_waitting: false,
      level_sell: 3,
      driver_priority_id: 0,
      group_priority_name: '',
      driver_priority_list: '',
      driver_limited: '2,6406,7887',
    },
  },
  {
    Trip: {
      id: 100726359,
      trip_status: 0,
      sold: 0,
      driver_buy: '',
      is_vat: 0,
      guests: 4,
      direction: 2,
      full_name_driver_owner: 'Nguyen DUng',
      time_start: '2025-10-30 14:00:00',
      time_sell: '2025-10-30 08:08:20',
      price_sell: 190,
      price_driver_priority: 0,
      price_driver_vip: 0,
      price_driver_normal: 190,
      type_car_name_id: 1,
      place_start:
        'HUDxx Linh Đàm, Linh Đường, Khu đô Thị Tây Nam Linh Đàm, Hoàng Liệt, Hoàng Mai, Hà Nội',
      place_end: 'Sân Bay Nội Bài (HAN), Sóc Sơn, Hà Nội',
      is_one_way: 1,
      time_sell_display: 29363460,
      total_time_sell_priority: 0,
      time_sell_driver_priority: '2025-10-30 11:00:00',
      time_sell_driver_priority_list: '2025-10-30 11:00:00',
      time_sell_driver_vip: '2025-10-30 11:00:00',
      time_sell_driver_normal: '1970-01-01 08:00:00',
      point: 0,
      point_time: 0,
      point_driver_priority: 0,
      point_driver_priority_list: 0,
      point_driver_vip: 0,
      point_driver_normal: 0,
      super_vip_drivers: '',
      note: 'Thân thiện, hỗ trợ hành lý',
      price_note: '',

      buy_button: false,
      display: true,
      is_waitting: true,
      level_sell: 3,
      driver_priority_id: 0,
      group_priority_name: '',
      driver_priority_list: '',
      driver_limited: '2,6406,7887',
    },
  },
  {
    Trip: {
      id: 100725825,
      trip_status: 0,
      sold: 0,
      driver_buy: '',
      is_vat: 0,
      guests: 2,
      direction: 1,
      full_name_driver_owner: 'Nguyen DUng',
      time_start: '2025-10-30 14:00:00',
      time_sell: '2025-10-30 11:00:00',
      price_sell: 170,
      price_driver_priority: 0,
      price_driver_vip: 0,
      price_driver_normal: 170,
      type_car_name_id: 1,
      place_start: 'Sân Bay Nội Bài, Hà Nội',
      place_end: 'xx Phố Miếu Đầm, Mễ Trì, Nam Từ Liêm, Hà Nội',
      is_one_way: 1,
      time_sell_display: 29363460,
      total_time_sell_priority: 0,
      time_sell_driver_priority: '2025-10-30 11:00:00',
      time_sell_driver_priority_list: '2025-10-30 11:00:00',
      time_sell_driver_vip: '2025-10-30 11:00:00',
      time_sell_driver_normal: '1970-01-01 08:00:00',
      point: 0,
      point_time: 0,
      point_driver_priority: 0,
      point_driver_priority_list: 0,
      point_driver_vip: 0,
      point_driver_normal: 0,
      super_vip_drivers: '',
      note: 'Xe mới, sạch sẽ',
      price_note: 'Giá trên đã bao gồm phí cao tốc, phí ra vào SB',

      buy_button: false,
      display: true,
      is_waitting: true,
      level_sell: 3,
      driver_priority_id: 0,
      group_priority_name: '',
      driver_priority_list: '',
      driver_limited: '2,6406,7887',
    },
  },
  {
    Trip: {
      id: 100685539,
      trip_status: 0,
      sold: 0,
      driver_buy: '',
      is_vat: 1,
      direction: 2,
      guests: 1,
      full_name_driver_owner: 'Nguyen DUng',
      time_start: '2025-10-30 13:40:00',
      time_sell: '2025-10-30 08:40:00',
      price_sell: 830,
      price_driver_priority: 0,
      price_driver_vip: 0,
      price_driver_normal: 830,
      type_car_name_id: 1,
      place_start: 'Sân Bay Nội Bài, Hà Nội',
      place_end: 'Thành Phố Ninh Bình, Ninh Bình',
      is_one_way: 1,
      time_sell_display: 29363440,
      total_time_sell_priority: 0,
      time_sell_driver_priority: '2025-10-30 08:40:00',
      time_sell_driver_priority_list: '2025-10-30 08:40:00',
      time_sell_driver_vip: '2025-10-30 08:40:00',
      time_sell_driver_normal: '1970-01-01 08:00:00',
      point: 4,
      point_time: 0,
      point_driver_priority: 0,
      point_driver_priority_list: 0,
      point_driver_vip: 0,
      point_driver_normal: 0,
      super_vip_drivers: '',
      note: '',
      price_note: 'Giá trên đã bao gồm phí cao tốc, phí ra vào SB',

      buy_button: true,
      display: true,
      is_waitting: false,
      level_sell: 3,
      driver_priority_id: 0,
      group_priority_name: '',
      driver_priority_list: '',
      driver_limited: '2,6406,7887',
    },
  },
  {
    Trip: {
      id: 100722639,
      trip_status: 0,
      is_vat: 0,
      sold: 0,
      driver_buy: '',
      guests: 4,
      direction: 2,
      full_name_driver_owner: 'Nguyen DUng',
      time_start: '2025-10-30 14:00:00',
      time_sell: '2025-10-30 08:08:20',
      price_sell: 190,
      price_driver_priority: 0,
      price_driver_vip: 0,
      price_driver_normal: 190,
      type_car_name_id: 1,
      place_start:
        'HUDxx Linh Đàm, Linh Đường, Khu đô Thị Tây Nam Linh Đàm, Hoàng Liệt, Hoàng Mai, Hà Nội',
      place_end: 'Sân Bay Nội Bài (HAN), Sóc Sơn, Hà Nội',
      is_one_way: 1,
      time_sell_display: 29363460,
      total_time_sell_priority: 0,
      time_sell_driver_priority: '2025-10-30 11:00:00',
      time_sell_driver_priority_list: '2025-10-30 11:00:00',
      time_sell_driver_vip: '2025-10-30 11:00:00',
      time_sell_driver_normal: '1970-01-01 08:00:00',
      point: 3,
      point_time: 0,
      point_driver_priority: 0,
      point_driver_priority_list: 0,
      point_driver_vip: 0,
      point_driver_normal: 0,
      super_vip_drivers: '',
      note: 'Không ngồi ghế cuối',
      price_note: 'Giá trên đã bao gồm phí cao tốc, phí ra vào SB',

      buy_button: false,
      display: true,
      is_waitting: true,
      level_sell: 3,
      driver_priority_id: 0,
      group_priority_name: '',
      driver_priority_list: '',
      driver_limited: '2,6406,7887',
    },
  },
  {
    Trip: {
      id: 100726078,
      group_type_car_name: 4,
      group_group_area_name: 'Hai Phong',
      sold: 0,
      driver_buy: 'Nguyễn Văn Long',
      is_vat: 0,
      direction: 1,
      full_name_driver_owner: 'Nguyen Dung',
      guests: 1,
      time_start: '2025-10-30 13:00:00',
      time_sell: '2025-10-30 08:50:00',
      price_sell: 160,
      place_start:
        'Trung Tâm Hội Nghị Quốc Gia Việt Nam, Mễ Trì, Từ Liêm, Hà Nội',
      place_end: 'Sân Bay Nội Bài (HAN), Sóc Sơn, Hà Nội',

      point: 2,

      note: 'Đón đúng giờ',
    },
  },
];
export const tranferPoints = [
  {
    id: '1',
    name: 'Nguyễn Văn Anh',
    date: '2025-10-30 13:00:00',
    point: 540,
    price: '50K/Điểm',
    phone: '0933 456 789',
  },
  {
    id: '2',
    name: 'Nguyễn Văn Anh',
    date: '2025-10-31 09:30:00',
    point: 540,
    price: '50K/Điểm',
    phone: '0933 456 789',
  },
  {
    id: '3',
    name: 'Nguyễn Văn Anh',
    date: '2025-11-01 20:45:00',
    point: 540,
    price: '50K/Điểm',
    phone: '0933 456 789',
  },
  {
    id: '4',
    name: 'Nguyễn Văn Anh',
    date: '2025-11-1 09:30:00',
    point: 540,
    price: '50K/Điểm',
    phone: '0933 456 789',
  },
  {
    id: '5',
    name: 'Nguyễn Văn Anh',
    date: '2025-11-1 09:30:00',
    point: 540,
    price: '50K/Điểm',
    phone: '0933 456 789',
  },
];
export const members = [
  { id: 1, full_name: 'nguyen van an', user_name: 'annv' },
  { id: 2, full_name: 'nguyen van an', user_name: 'annv' },
  { id: 3, full_name: 'nguyen van an', user_name: 'annv' },
  { id: 4, full_name: 'nguyen van an', user_name: 'annv' },
  { id: 5, full_name: 'nguyen van an', user_name: 'annv' },
  { id: 6, full_name: 'nguyen van an', user_name: 'annv' },
  { id: 7, full_name: 'nguyen van an', user_name: 'annv' },
  { id: 8, full_name: 'nguyen van an', user_name: 'annv' },
];
